routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home_page');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('article/{id}', 'ArticlesController@show');
Route::get('logout', 'Auth\LoginController@logout');
//admin routes
Route::group(['prefix'=>'admin','middleware'=>'auth'], function(){
    Route::get('/', 'AdminController@index');
    //articles routes
    Route::resource('articles', 'ArticlesController');
    Route::get('/articles/{id}/delete', 'ArticlesController@destroy');
    //categories routes
    Route::resource('categories', 'CategoriesController');
    Route::get('/categories/{id}/delete', 'CategoriesController@destroy');

});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    public function categories()
    {
        return $this->belongsTo('App\Category','category_id','id');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Validator;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::with('categories')->orderBy('order', 'asc')->
        orderBy('id', 'desc')->get();
        return view('admin/article/all_articles', ['articles' => $articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin/article/add_edit', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|max:255',
            'description' => 'required',
            'publish' => 'required',
            'featured' => 'required',
            'image' => 'required',
            'priority' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect('admin/articles/create')
                ->withErrors($validator)
                ->withInput();
        }
        $articleInstance = new Article;
        $articleInstance->title = $request->title;
        $articleInstance->body = $request->description;
        $articleInstance->published = $request->publish[0];
        $articleInstance->featured = $request->featured[0];
        //image sector
        $file = $request->file('image');
        $articleInstance->image = $file->getClientOriginalName();
        $file->move('images', $file->getClientOriginalName());
        //
        $articleInstance->order = $request->priority;
        $articleInstance->created_by = Auth::user()->id;
        $articleInstance->category_id = $request->category;
        if ($articleInstance->save()) {
            return redirect('admin/articles');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::with('categories')->find($id);
        return view('article', ['article' => $article]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $articleData = Article::find($id);
        return view('admin/article/add_edit', ['categories' => $categories, 'articleData' => $articleData]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|max:255',
            'description' => 'required',
            'publish' => 'required',
            'featured' => 'required',
            'priority' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect('admin/articles/'.$id.'/edit')
                ->withErrors($validator)
                ->withInput();
        }
        $articleInstance = Article::find($id);
        $articleInstance->title = $request->title;
        $articleInstance->body = $request->description;
        $articleInstance->published = $request->publish[0];
        $articleInstance->featured = $request->featured[0];
        //image sector
        if ($request->has('image')) {
            $file = $request->file('image');
            $articleInstance->image = $file->getClientOriginalName();
            $file->move('images', $file->getClientOriginalName());
        }
        //
        $articleInstance->order = $request->priority;
        $articleInstance->created_by = Auth::user()->id;
        $articleInstance->category_id = $request->category;
        if ($articleInstance->update()) {
            return redirect('admin/articles');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Article::find($id)->delete()) {
            return redirect('/admin/articles');
        }
    }
}

resources/views/admin/article/add_edit.blade.php
@include('admin.nav')
<script src="{{url('js/ckeditor_3/ckeditor.js')}}"></script>
<div class="container-fluid main-container">
    @include('admin.side_admin')
    <div class="col-md-10 content">
        <div class="panel panel-default">
            <div class="panel-heading">
                Add Edit Article
            </div>
            <div class="panel-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" enctype="multipart/form-data"
                      @if(!isset($articleData))
                      action="{{route('articles.store')}}"
                      @else action="{{route('articles.update',$articleData->id)}}" @endif
                >
                    {{ csrf_field() }}
                    @if(isset($articleData))
                        {{ method_field('PATCH') }}
                    @endif
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" name="title" class="form-control" @if(isset($articleData))
                        value="{{$articleData->title}} @endif">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" id="editor1" rows="10" cols="80">
                            @if(isset($articleData))
                                {{$articleData->body}}
                            @endif
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label>Publish</label><br>
                        <input type="radio" name="publish[]" @if(isset($articleData) and $articleData->published == 1) checked @endif
                               value="1">publish<br>
                        <input type="radio" name="publish[]" @if(isset($articleData) and $articleData->published == 0) checked @endif
                        value="0">un publish
                    </div>
                    <div class="form-group">
                        <label>Featured</label><br>
                        <input type="radio" name="featured[]" @if(isset($articleData) and $articleData->featured ==
                        'featured') checked @endif
                        value="featured">Featured<br>
                        <input type="radio" name="featured[]" @if(isset($articleData) and $articleData->featured == 'not_featured') checked
                               @endif
                        value="not_featured">not Featured
                    </div>
                    <div class="form-group">
                        <label>image</label><br>
                        <input type="file" name="image">
                    </div>
                    <div class="form-group">
                        <label>Enter order(priority) of article in number</label><br>
                        <input type="number" @if(isset($articleData->order)) value="{{$articleData->order}}" @endif
                               class="form-control"
                               name="priority"><br>
                    </div>
                    <div class="form-group">
                        <label>Category</label><br>
                        <select name="category" class="form-control">
                            @foreach($categories as $category)
                                <option @if(isset($articleData) and $articleData->category_id == $category->id)
                                        selected
                                        @endif
                                value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" @if(isset($articleData)) value="Update" @else
                        value="save" @endif>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace("editor1");
</script>

resources/views/admin/article/all_articles.blade.php
@include('admin.nav')
<div class="container-fluid main-container">
    @include('admin.side_admin')
    @foreach ($articles->chunk(2) as $chunkedArticle)
        <div class="row">
            @foreach($chunkedArticle as $article)
                <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" alt="Bootstrap Thumbnail First"
                             width="300" src="{{url("images/$article->image")}}"/>
                        <div class="card-block">
                            <h5 class="card-title">
                                {{$article->title}}
                            </h5>
                            <p class="card-text">
                                category: {{$article->categories->name}}
                            </p>
                            <p>
                                <a class="btn btn-primary" href="{{url("admin/articles/$article->id/edit")
                                }}">Edit</a>
                                <a class="btn" href="{{url("/admin/articles/$article->id/delete")}}">Delete</a>
                            </p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endforeach
</div>