routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home_page');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('article/{id}', 'ArticlesController@show');
Route::get('logout', 'Auth\LoginController@logout');
//admin routes
Route::group(['prefix'=>'admin','middleware'=>'auth'], function(){
    Route::get('/', 'AdminController@index');
    //articles routes
    Route::resource('articles', 'ArticlesController');
    Route::get('/articles/{id}/delete', 'ArticlesController@destroy');
    //categories routes
    Route::resource('categories', 'CategoriesController');
    Route::get('/categories/{id}/delete', 'CategoriesController@destroy');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Validator;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(9);
        return view('admin.category.all_categories', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.add_edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:70'
        ]);
        if ($validator->fails()) {
            return redirect('admin/categories/create')
                ->withErrors($validator)
                ->withInput();
        }
        $categoryInstance = new Category();
        $categoryInstance->name = $request->name;
        $categoryInstance->created_by = Auth::user()->id;
        if ($categoryInstance->save()) {
            return redirect('admin/categories');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoryData = Category::find($id);
        return view('admin.category.add_edit', ['categoryData' => $categoryData]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:70'
        ]);
        if ($validator->fails()) {
            return redirect('admin/categories/create')
                ->withErrors($validator)
                ->withInput();
        }
        $categoryInstance = Category::find($id);
        $categoryInstance->name = $request->name;
        if ($categoryInstance->update()) {
            return redirect('admin/categories');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Category::find($id)->delete()){
            return redirect('/admin/categories');
        }
    }
}

resources/views/admin/category/add_edit.blade.php
@include('admin.nav')
<div class="container-fluid main-container">
    @include('admin.side_admin')
    <div class="col-md-10 content">
        <div class="panel panel-default">
            <div class="panel-heading">
                Add Edit Category
            </div>
            <div class="panel-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST"
                      @if(!isset($categoryData))
                      action="{{route('categories.store')}}"
                      @else action="{{route('categories.update',$categoryData->id)}}" @endif
                >
                    {{ csrf_field() }}
                    @if(isset($categoryData))
                        {{ method_field('PATCH') }}
                    @endif
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" @if(isset($categoryData->name))
                        value="{{$categoryData->name}}" @endif
                               class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" @if(!isset($categoryData)) value="Save"
                               @else value="update" @endif class="form-control">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/category/all_categories.blade.php
@include('admin.nav')
<div class="container-fluid main-container">
    @include('admin.side_admin')
    <div class="col-md-10 content">
        <div class="panel panel-default">
            <div class="panel-heading">
                All Categories
            </div>
            <div class="panel-body">
                @foreach ($categories as $category)
                    <div class="col-md-8">
                        {{ $category->name }}
                    </div>
                    <div class="col-md-4">
                        <a href="{{url("/admin/categories/$category->id/edit")}}" class="btn btn-info">Edit</a>
                        <a href="{{url("/admin/categories/$category->id/delete")}}" class="btn btn-danger">Delete</a>
                    </div>
                @endforeach
                {{ $categories->links() }}
            </div>
        </div>
    </div>
</div>